config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  Rails.application.routes.draw do
    root "main#index"

    get "/login",  to: "sessions#new"
    post "/login",  to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    get "/register", to: "user#new"
    post "/register", to: "user#create"
    get "/user_update", to: "user#get"
    post "/user_update", to: "user#update"
    post "/user_lock/:id", to: "user#lock", as: "user_lock"
    post "/user_unlock/:id", to: "user#unlock", as: "user_unlock"
    get "/user_detail/:id", to: "user#detail", as: "user_detail"

    get "/request/list", to: "request#list", as: "request_list"
    post "/request_accep/:id", to: "request#accep", as: "request_accep"
    post "/request_denial/:id", to: "request#denial", as: "request_denial"

    get "/request/:id", to: "request#new", as: "request"
    post "/request/:id", to: "request#create", as: "request_save"

    get "/timetable", to: "timetable#list"

    get "/support", to: "support#list"
    post "/support", to: "support#create"

    post "/support/processing/:id", to: "support#processing", as: "support_processing"
    post "/support/closed/:id", to: "support#closed", as: "support_closed"

  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  # GET /index
  def index
    @user = User.all.order(:id)
    @current_user.reload
    if @current_user.role == 'student'
      @user = @user.where(role: 'teacher')
    end
    search_user
    @user = @user.paginate(page: params[:page], per_page: 3)

    @request = Request.joins("JOIN users ON users.id = requests.student_id")
                   .where(teacher_id: @current_user.id)
                   .select("requests.*, users.full_name AS full_name")
    @request = @request.paginate(page: params[:page], per_page: 3)
  end

  def search_user
    if params[:commit].nil?
      if @current_user.role == 'student'
        cap_hoc = tinh_cap_hoc(@current_user.date_of_birth)
        @user = @user.left_joins(:teacher_profile)
                    .where("teacher_profiles.subjects::text ILIKE ?", "%#{cap_hoc}%")
      else
        @user = @user.left_joins(:teacher_profile)
      end
      return
    end
    if params[:query].present?
      q = "%#{params[:query]}%"
      @user = @user.where("full_name LIKE ? OR email LIKE ?", q, q)
    end
    if params[:location].present?
      q = "%#{params[:location]}%"
      @user = @user.joins(:teacher_profile)
                  .where("teacher_profiles.location::text ILIKE ?", "%#{q}%")
    end
    if params[:mon_hoc].present? && params[:cap_hoc].present?
      @user = @user.joins(:teacher_profile)
                  .where("teacher_profiles.subjects ->> :key = :value",
                         key: params[:mon_hoc],
                         value: params[:cap_hoc])
    elsif params[:mon_hoc].present?
      @user = @user.joins(:teacher_profile)
                  .where("teacher_profiles.subjects ? :key", key: params[:mon_hoc])
    elsif params[:cap_hoc].present?
      @user = @user.joins(:teacher_profile)
                  .where("teacher_profiles.subjects::text ILIKE ?", "%#{params[:cap_hoc]}%")
    end
    if params[:role].present?
      @user = @user.where(role: params[:role])
    end
  end
end

app/views/main/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Find user</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-..." crossorigin="anonymous">
</head>
<body class="index">

<%= render "common/header" %>

<%= render "common/notice" %>

<% if current_user &&  (current_user.role == "admin" || current_user.role == "student")%>

  <!-- Thanh tìm kiếm -->
  <%= form_with url: root_path, method: :get, local: true, class: "search" do |f| %>
    <div>
      <%= f.text_field :query, value: params[:query], class: "form-control", placeholder: "Nhập tên hoặc email..." %>
    </div>

    <div>
      <%= f.text_field :location, value: params[:location], class: "form-control", placeholder: "Nhập khu vực..." %>
    </div>

    <div>
      <% if current_user.role == "admin" %>
        <%= f.select :role, options_for_select(
            [["Tất cả", ""], ["Admin", "admin"], ["Gia sư", "teacher"], ["Học viên", "student"]],
            selected: params[:role]
        ), {}, class: "form-select" %>
      <%end %>
    </div>
    <% cap_hoc = tinh_cap_hoc(current_user.date_of_birth) if current_user.role == 'student' %>
    <%= f.select :cap_hoc, options_for_select(
        [["Cấp học", ""], ["Cấp 1", "Cấp 1"], ["Cấp 2", "Cấp 2"], ["Cấp 3", "Cấp 3"]],
        selected: params[:cap_hoc] || cap_hoc
    ), {}, class: "form-select w-auto" %>

    <%= f.select :mon_hoc, options_for_select(
        [["Môn học", ""], %w(Toán Toán), %w(Lý Lý), %w(Hóa Hóa), %w(Sinh Sinh), %w(Văn Văn), %w(Sử Sử), %w(Địa Địa), %w(Anh Anh)],
        selected: params[:mon_hoc]
    ), {}, class: "form-select w-auto" %>
    <div>
      <%= f.submit "Tìm kiếm", class: "btn btn-success w-100" %>
    </div>

    <div>
      <%= link_to "Đặt lại", root_path, class: "btn btn-success w-100" %>
    </div>
  <% end %>


  <h2>
    <% if current_user.role == "teacher" %>
      Danh sách lời mời
    <% elsif current_user.role == "student" %>
      Danh sách giáo viên
    <% elsif current_user.role == "admin" %>
      Danh sách user
    <% end %>
  </h2>

  <% if @user.present? %>
    <div class="table-container">
      <table>
        <thead>
        <tr>
          <th>Họ tên</th>
          <th>Email</th>
          <th>Số điện thoại</th>
          <%= content_tag(:th, "Chuyên môn") if current_user.role == "student" %>
          <th class="text-center">Hành động</th>
        </tr>
        </thead>
        <tbody>
        <% @user.each do |user| %>
          <tr>
            <td><%= user.full_name %></td>
            <td><%= user.email %></td>
            <td><%= user.phone_number %></td>
            <% if current_user.role == "student" %>
              <td>
                <% if user.teacher_profile&.subjects.present? %>
                  <ul class="d-inline-block m-0 ps-3">
                    <% user.teacher_profile.subjects.each do |subject, level| %>
                      <li><%= "#{subject} - #{level}" %></li>
                    <% end %>
                  </ul>
                <% else %>
                  <span>Chưa có môn học</span>
                <% end %>
              </td>
            <% end %>
            <td class="<%= 'locked' if user.is_locked == true %> text-center d-flex justify-content-center">
              <%= link_to user_detail_path(user), method: :get, class: "btn btn-primary" do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                  <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0"></path>
                  <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7"></path>
                </svg>
                Xem chi tiết
              <%end %>
              <%if @current_user.role == 'admin' %>
                <%= button_to user_lock_path(user), method: :post, class: "btn btn-outline-danger" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-lock2-fill" viewBox="0 0 16 16">
                    <path d="M7 6a1 1 0 0 1 2 0v1H7z"></path>
                    <path d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2m-2 6v1.076c.54.166 1 .597 1 1.224v2.4c0 .816-.781 1.3-1.5 1.3h-3c-.719 0-1.5-.484-1.5-1.3V8.3c0-.627.46-1.058 1-1.224V6a2 2 0 1 1 4 0"></path>
                  </svg>
                  Lock
                <%end %>

                <%= button_to user_unlock_path(user), method: :post, class: "btn btn-success" do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-lock2-fill" viewBox="0 0 16 16">
                  <path d="M7 6a1 1 0 0 1 2 0v1H7z"></path>
                  <path d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2m-2 6v1.076c.54.166 1 .597 1 1.224v2.4c0 .816-.781 1.3-1.5 1.3h-3c-.719 0-1.5-.484-1.5-1.3V8.3c0-.627.46-1.058 1-1.224V6a2 2 0 1 1 4 0"></path>
                </svg>
                Open
                <%end %>
              <%end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="pagination">
      <%= will_paginate @user %>
    </div>
  <% else %>
    <p style="text-align:center;">Chưa có ai.</p>
  <% end %>
<% elsif current_user && current_user.role == "teacher" %>
  <h2>Danh sách lời mời</h2>
  <% if @request.present? %>
    <div class="table-container">
      <table>
        <thead>
        <tr>
          <th>Họ tên</th>
          <th>Môn học</th>
          <th>Cấp học</th>
          <th>Note</th>
          <th>Học phí đề xuất</th>
          <th>Địa điểm</th>
          <th>Lịch học</th>
          <th>Status</th>
          <th class="text-center">Hành động</th>
        </tr>
        </thead>
        <tbody>
        <% @request.each do |req| %>
          <tr>
            <td><%= req.full_name %></td>
            <td><%= req.subject %></td>
            <td><%= req.grade_level %></td>
            <td><%= req.requirement_detail %></td>
            <td><%= req.budget %></td>
            <td><%= req.location %></td>
            <td>
              <% req.schedule.each do |date, time| %>
                <%= "#{date} - #{time}" %>
              <% end %>
            </td>
            <td><%= req.status %></td>
            <td class="text-center d-flex justify-content-center">
              <% if req.status == 'open' %>
                <%= button_to "Chấp nhận", request_accep_path(req), method: :post, class: "btn btn-primary" %>
                <%= button_to "Từ chối", request_denial_path(req), method: :post, class: "btn btn-outline-danger" %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="pagination">
      <%= will_paginate @request %>
    </div>
  <% else %>
    <p style="text-align:center;">Chưa có lời mời.</p>
  <% end %>
<% end %>

<% if current_user.role == "teacher" || current_user.role == "student"%>
  <div class="form-actions mt-3" style="padding-left: 60px">
    <%= link_to "Thời khóa biểu", timetable_path, method: :get, class: "btn btn-success" %>
  </div>
<% end %>

</body>
</html>