config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  Rails.application.routes.draw do
    root "main#index"

    get "/login",  to: "sessions#new"
    post "/login",  to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    get "/register", to: "user#new"
    post "/register", to: "user#create"
    get "/user_update", to: "user#get"
    post "/user_update", to: "user#update"
    post "/user_lock/:id", to: "user#lock", as: "user_lock"
    post "/user_unlock/:id", to: "user#unlock", as: "user_unlock"
    get "/user_detail/:id", to: "user#detail", as: "user_detail"

    get "/request/list", to: "request#list", as: "request_list"
    post "/request_accep/:id", to: "request#accep", as: "request_accep"
    post "/request_denial/:id", to: "request#denial", as: "request_denial"

    get "/request/:id", to: "request#new", as: "request"
    post "/request/:id", to: "request#create", as: "request_save"

    get "/timetable", to: "timetable#list"

    get "/support", to: "support#list"
    post "/support", to: "support#create"

    post "/support/processing/:id", to: "support#processing", as: "support_processing"
    post "/support/closed/:id", to: "support#closed", as: "support_closed"

  end

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :student, class_name: "User"
  belongs_to :teacher, class_name: "User"
  has_one :timetable, dependent: :destroy

  enum status: {
      open: "open",
      accepted: "accepted",
      rejected: "rejected",
      closed: "closed"
  }

  validates :subject, :budget, presence: true
  validates :budget, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true

end

app/controllers/request_controller.rb
class RequestController < ApplicationController
  before_action :set_teacher, only: [:new, :create]

  def new
    # set_teacher
  end

  def create
    # set_teacher
    old_request = Request.where(student_id: current_user)
    # binding.pry
    if params[:teacher_full_name].blank? || params[:mon_cap].blank? || params[:date_time].blank? || params[:location].blank? || params[:budget].blank?
      flash.now[:alert] = "Vui lòng nhập đầy đủ thông tin!"
      render :new, status: :unprocessable_entity
      return
    end
    subject = params[:mon_cap].split(' - ').first.gsub('_', ' ')
    grade_level = params[:mon_cap].split(' - ').last
    if old_request.where(subject: subject).present?
      flash[:alert] = "Đã gửi lời mời cho môn này rồi!"
      render :new, status: :unprocessable_entity
      return
    end

    old_lich_hoc = []
    old_lich_hoc = old_request.pluck(:schedule).map { |date, time| ["#{date} - #{time}"] } if old_request.present?
    if old_lich_hoc.present? && old_lich_hoc.include?(params[:date_time])
      flash[:alert] = "Đã gửi lời mời cho thời gian này rồi!"
      render :new, status: :unprocessable_entity
      return
    end
    date_time = params[:date_time].split(' - ')
    date_time = { date_time.first.gsub('_', ' ') => date_time.last.gsub('_', ' ') }
    flash[:notice] = "Đăng kí thành công!"
    Request.create!(
      student_id: @current_user.id,
      teacher_id: @teacher.id,
      subject: subject,
      grade_level: grade_level,
      requirement_detail: params[:req_detail],
      budget: params[:budget],
      location: params[:location],
      schedule: date_time,
      status: 'open'
    )
    redirect_to request_list_path
  end

  def list
    if @current_user.role == 'student'
      @request = Request.joins("JOIN users ON users.id = requests.teacher_id")
                     .where(student_id: @current_user.id)
                     .select("requests.*, users.full_name AS full_name")
    else
      @request = Request.joins("JOIN users ON users.id = requests.teacher_id")
                     .where(teacher_id: @current_user.id)
                     .select("requests.*, users.full_name AS full_name")
    end
    @request = @request.paginate(page: params[:page], per_page: 3)
  end

  def accep
    req = Request.find(params[:id])
    req.update!(status: "accepted")

    Timetable.create!(
        teacher_id: req.teacher_id,
        student_id: req.student_id,
        subject: req.subject,
        schedule: req.schedule,
        status: "open",
        location: req.location
    )

    redirect_to root_path
  end

  def denial
    Request.where(id: params[:id]).update_all(status: 'rejected')
    redirect_to root_path
  end

  private

  def set_teacher
    @teacher = User.find(params[:id])
  end

end

app/views/request/list.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Find user</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-..." crossorigin="anonymous">
</head>
<body class="index">

<%= render "common/header" %>

<%= render "common/notice" %>

<h2>Danh sách lời mời</h2>
<% if @request.present? %>
  <div class="table-container">
    <table>
      <thead>
      <tr>
        <th>Họ tên</th>
        <th>Môn học</th>
        <th>Cấp học</th>
        <th>Note</th>
        <th>Học phí đề xuất</th>
        <th>Địa điểm</th>
        <th>Lịch học</th>
        <th>Status</th>
      </tr>
      </thead>
      <tbody>
      <% @request.each do |req| %>
        <tr>
          <td><%= req.full_name %></td>
          <td><%= req.subject %></td>
          <td><%= req.grade_level %></td>
          <td><%= req.requirement_detail %></td>
          <td><%= req.budget %></td>
          <td><%= req.location %></td>
          <td>
            <% req.schedule.each do |date, time| %>
              <%= "#{date} - #{time}" %>
            <% end %>
          </td>
          <td><%= req.status %></td>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="pagination">
    <%= will_paginate @request %>
  </div>
<% else %>
  <p style="text-align:center;">Chưa có lời mời.</p>
<% end %>
<div class="form-actions mt-3" style="margin-left: 60px">
  <%= link_to "Quay lại", root_path, class: "btn btn-secondary" %>
</div>
</body>
</html>

app/views/request/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Find user</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-..." crossorigin="anonymous">
</head>
<body class="index">

<%= render "common/header" %>

<h2>Tạo lời mời</h2>

<%= render "common/notice" %>
<%= form_with url: request_save_path(@teacher), method: :post, local: true, class: "update-form" do |f| %>
  <div class="form-group">
    <%= f.label :teacher_full_name, "Giáo viên" %>
    <%= f.text_field :teacher_full_name, class: "form-control", value: @teacher.full_name, readonly: true %>
  </div>

  <div class="form-group">
  <%= f.label :mon_cap, "Chọn môn - cấp học" %>
    <%= f.select :mon_cap,
                 options_for_select(
                     [["Chọn", ""]] +
                         @teacher.teacher_profile.subjects.map { |subject, level| ["#{subject} - #{level}"] },
                     selected: params[:mon_cap]
                 ),
                 {},
                 class: "form-select w-25"
    %>
  </div>

  <div class="form-group">
    <%= f.label :date_time, "Chọn thời gian học" %>
    <%= f.select :date_time,
                 options_for_select(
                     [["Chọn", ""]] +
                         @teacher.teacher_profile.availability.map { |date, time| ["#{date} - #{time}"] },
                     selected: params[:date_time]
                 ),
                 {},
                 class: "form-select w-25"
    %>
  </div>

  <div class="form-group">
    <%= f.label :req_detail, "Chi tiết lời mời" %>
    <%= f.text_field :req_detail, class: "form-control", placeholder: "Nhập chi tiết ..." %>
  </div>

  <div class="form-group">
    <%= f.label :budget, "Kinh phí đề xuất (VND/1 giờ)" %>
    <%= f.text_field :budget, class: "form-control", placeholder: "Nhập kinh phí...", value: @teacher.teacher_profile.hourly_rate %>
  </div>

  <div class="form-group">
    <%= f.label :location, "Địa điểm" %>
    <%= f.text_field :location, class: "form-control", placeholder: "Nhập địa điểm..." %>
  </div>

  <div class="form-actions mt-3">
    <%= f.submit "Gửi lời mời", class: "btn btn-success" %>
    <%= link_to "Danh sách lời mời", request_list_path, class: "btn btn-success" %>
    <%= link_to "Hủy", user_detail_path(@teacher), class: "btn btn-secondary" %>
  </div>
<% end %>


</body>
</html>