config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  Rails.application.routes.draw do
    root "main#index"

    get "/login",  to: "sessions#new"
    post "/login",  to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    get "/register", to: "user#new"
    post "/register", to: "user#create"
    get "/user_update", to: "user#get"
    post "/user_update", to: "user#update"
    post "/user_lock/:id", to: "user#lock", as: "user_lock"
    post "/user_unlock/:id", to: "user#unlock", as: "user_unlock"
    get "/user_detail/:id", to: "user#detail", as: "user_detail"

    get "/request/list", to: "request#list", as: "request_list"
    post "/request_accep/:id", to: "request#accep", as: "request_accep"
    post "/request_denial/:id", to: "request#denial", as: "request_denial"

    get "/request/:id", to: "request#new", as: "request"
    post "/request/:id", to: "request#create", as: "request_save"

    get "/timetable", to: "timetable#list"

    get "/support", to: "support#list"
    post "/support", to: "support#create"

    post "/support/processing/:id", to: "support#processing", as: "support_processing"
    post "/support/closed/:id", to: "support#closed", as: "support_closed"

  end

end

app/views/common/_choose_subject.html.erb
<div class="dynamic-field-container" data-field-name="subjects">
  <%= "Chọn môn học" %>
  <% (@current_user.teacher_profile&.subjects || {}).each do |subject, level| %>
    <div class="field-row mb-2 d-flex align-items-center">
      <input type="text"
             name="user[teacher_profile_attributes][subjects][<%= subject %>]"
             value="<%= subject %>"
             class="form-control me-2 w-50"
             placeholder="Tên môn học (VD: Toán)">
      <select name="user[teacher_profile_attributes][subjects][<%= subject %>]"
              class="form-select w-25">
        <option value="Cấp 1" <%= "selected" if level == "Cấp 1" %>>Cấp 1</option>
        <option value="Cấp 2" <%= "selected" if level == "Cấp 2" %>>Cấp 2</option>
        <option value="Cấp 3" <%= "selected" if level == "Cấp 3" %>>Cấp 3</option>
      </select>
      <button type="button" class="btn btn-danger btn-sm ms-2 remove-row">–</button>
    </div>
  <% end %>
</div>

<button type="button" id="add-subject" class="btn btn-secondary mt-2">+ Thêm môn</button>

app/views/common/_choose_time.html.erb
<div class="dynamic-field-container" data-field-name="availability">
  <%= "Chọn thời gian rảnh" %>
  <% (@current_user.teacher_profile&.availability || {}).each do |day, session| %>
    <div class="field-row mb-2 d-flex align-items-center">
      <input type="text"
             name="user[teacher_profile_attributes][availability][<%= day %>]"
             value="<%= day %>"
             class="form-control me-2 w-50"
             placeholder="Ngày trong tuần (VD: Thứ 2)">
      <select name="user[teacher_profile_attributes][availability][<%= day %>]"
              class="form-select w-25">
        <option value="Buổi sáng" <%= "selected" if session == "Buổi sáng" %>>Buổi sáng</option>
        <option value="Buổi chiều" <%= "selected" if session == "Buổi chiều" %>>Buổi chiều</option>
        <option value="Buổi tối" <%= "selected" if session == "Buổi tối" %>>Buổi tối</option>
      </select>
      <button type="button" class="btn btn-danger btn-sm ms-2 remove-row">–</button>
    </div>
  <% end %>
</div>

<button type="button" id="add-availability" class="btn btn-secondary mt-2">+ Thêm ngày</button>

app/views/common/_header.html.erb
<div class="header">
  <div>
    <%= link_to root_path, class: "d-flex text-decoration-none" do %>
      <%= image_tag "logo.jpg", alt: "Ảnh đại diện", class: "img-thumbnail", width: 100 %>
    <p>Find user</p>
    <% end %>
  </div>
  <div>
    <% if current_user %>
      <p><%= current_user.role %> - <%= current_user&.full_name %></p>

      <%= button_to support_path, method: :get, class: "btn-logout", alt: "help" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info" viewBox="0 0 16 16">
          <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
        </svg>
      <% end %>
      <%= button_to user_update_path, method: :get, class: "btn-logout", alt: "Logout" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
          <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z"/>
        </svg>
      <% end %>
      <%= button_to logout_path, method: :delete, class: "btn-logout", alt: "Info" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
             class="bi bi-box-arrow-left" viewBox="0 0 16 16">
          <path fill-rule="evenodd"
                d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0z"></path>
          <path fill-rule="evenodd"
                d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708z"></path>
        </svg>
      <% end %>
      </div>
    <% end %>
    </div>

app/views/common/_notice.html.erb
<% if flash[:alert] %>
  <div class="alert"><%= flash[:alert] %></div>
<% end %>
<% if flash[:notice] %>
  <div style="color:green;text-align:center;"><%= flash[:notice] %></div>
<% end %>

app/views/common/_update_profile.html.erb
<%= f.fields_for :teacher_profile do |tp| %>
  <div class="form-group">
    <%= tp.label :bio, "Giới thiệu" %>
    <%= tp.text_field :bio, class: "form-control", placeholder: "Nhập bio..." %>
  </div>

  <div class="form-group">
    <%= tp.label :education_level, "Trình độ" %>
    <%= tp.text_field :education_level, class: "form-control", placeholder: "Nhập trình độ..." %>
  </div>

  <div class="form-group">
    <%= tp.label :experience_years, "Số năm kinh nghiệm" %>
    <%= tp.text_field :experience_years, class: "form-control", placeholder: "Nhập số năm kinh nghiệm..." %>
  </div>

  <div class="form-group">
    <%= tp.label :location, "Tỉnh/TP" %>
    <%= tp.text_field :location, class: "form-control", placeholder: "Nhập tỉnh/TP hiện tại..." %>
  </div>

  <div class="form-group">
    <%= tp.label :hourly_rate, "Offer" %>
    <%= tp.text_field :hourly_rate, class: "form-control", placeholder: "Nhập offer theo giờ..." %>
  </div>

  <%= render "common/choose_subject" %>

  <%= render "common/choose_time" %>
<% end %>